name: Deploy React App

on: 
    workflow_run:
        workflows: ["CI Pipeline"]
        types:
            - completed
    
jobs:
    deploy:
        name: Deploy React App
        runs-on: ubuntu-latest

        permissions:
            contents: read
            pull-requests: write

        steps:
            - name: Checkout Code
              uses: actions/checkout@v3
    
            - name: Restore Node Modules
              uses: actions/cache@v3
              with:
                path: ~/.yarn
                key: yarn-${{ runner.os }}-${{ hashFiles('**/yarn.lock') }}

            # Step 3: Download Build Output
            - name: Download Build Output
              uses: actions/download-artifact@v4
              with:
                name: build-output
                path: build

            # Step 4: Start the Server
            - name: Start React App
              run: |
                nohup yarn serve -s build &
                sleep 5
                curl http://localhost:3000

            # Step 5: Install ngrok
            - name: Install ngrok
              run: npm install -g ngrok

            - name: Expose with ngrok
              run: |
                ngrok authtoken ${{ secrets.NGROK_AUTH_TOKEN }}
                ngrok http 3000
                sleep 5
                curl http://localhost:3000

            - name: Completed Deployment
              run: echo "Deployment Completed Successfully"

            - name: Get ngrok URL
              run : |
                URL=$(curl -s http://localhost:3000 | jq -r '.tunnels[0].public_url')
                echo "🔗 Public URL: $URL"

            # ✅ Keep ngrok Running
            - name: Keep Server Alive
              run: |
                while true; do
                    curl -s http://localhost:3000
                    sleep 30
                done
                