name: Deploy React App

on: 
    workflow_run:
        workflows: ["CI Pipeline"]
        types:
            - completed
    
jobs:
    deploy:
        name: Deploy React App
        runs-on: ubuntu-latest

        permissions:
            contents: write
            actions: write

        steps:
            - name: Checkout Code
              uses: actions/checkout@v3

            - name: Restore Node Modules
              uses: actions/cache@v3
              with:
                path: ~/.npm # ✅ Restore npm files
                key: npm-${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}
                restore-keys: |
                  npm-${{ runner.os }}-
                
            - name: Install Dependencies
              run: npm install

            - name: Wait for Artifact
              run: sleep 6

            - name: Debug Artifact List
              env:
                GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              run: gh run view ${{ github.run_id }} --log

            - name: Download Build Output
              uses: actions/download-artifact@v4
              with:
                name: build-output
                path: build
                run-id: ${{ github.event.workflow_run.id }}

            # Step 4: Start the Server
            - name: Start React App
              run: |
                nohup npx serve -s build &
                sleep 5
                curl http://localhost:3000

            # Step 5: Install ngrok
            - name: Install ngrok
              run: npm install -g ngrok

            - name: Expose with ngrok
              run: |
                ngrok authtoken ${{ secrets.NGROK_AUTH_TOKEN }}
                ngrok http 3000 &
                sleep 5
                curl http://localhost:4040/api/tunnels

            - name: Completed Deployment
              run: echo "Deployment Completed Successfully"

            - name: Get ngrok URL
              run: |
                URL=$(curl -s http://localhost:4040/api/tunnels | jq -r '.tunnels[0].public_url')
                echo "🔗 Public URL: $URL"

            # ✅ Keep ngrok Running
            - name: Keep Server Alive
              run: |
                while true; do
                    curl -s http://localhost:4040/api/tunnels
                    sleep 30
                done
                
