name: Deploy React App

on: 
    workflow_run:
        workflows: ["CI Pipeline"]
        types: [completed]
    
jobs:
    deploy:
        name: Deploy React App
        runs-on: ubuntu-latest

        permissions:
            contents: write
            actions: write

        steps:
            - name: Checkout Code
              uses: actions/checkout@v3

            - name: Restore Node Modules
              uses: actions/cache@v3
              with:
                path: ~/.npm # ✅ Restore npm files
                key: npm-${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}
                restore-keys: |
                  npm-${{ runner.os }}-
                
            - name: Install Dependencies
              run: npm install

            - name: Wait and Download Artifact
              env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              run: |
                echo "⏳ Waiting for artifact to be available..."
                for i in {1..5}; do
                  if gh run view ${{ github.event.workflow_run.id }} --log; then
                    echo "✅ Artifact is ready, downloading..."
                    break
                  else
                    echo "🚨 Artifact not ready yet, retrying in 5s..."
                    sleep 5
                  fi
                done
      
            # ✅ Download artifact with retry
            - name: Download Build Output
              uses: actions/download-artifact@v4
              with:
                name: build-output
                path: build
      
            # ✅ Confirm artifact files exist
            - name: Debug Downloaded Files
              run: ls -R build || echo "🚨 No files downloaded!"

            - name: Download Build Output
              uses: actions/download-artifact@v4
              with:
                name: build-output
                path: build
                run-id: ${{ github.event.workflow_run.id }}

            # Step 4: Start the Server
            - name: Start React App
              run: |
                nohup npx serve -s build &
                sleep 5
                curl http://localhost:3000

            # Step 5: Install ngrok
            - name: Install ngrok
              run: npm install -g ngrok

            - name: Expose with ngrok
              run: |
                ngrok authtoken ${{ secrets.NGROK_AUTH_TOKEN }}
                ngrok http 3000 &
                sleep 5
                curl http://localhost:4040/api/tunnels

            - name: Completed Deployment
              run: echo "Deployment Completed Successfully"

            - name: Get ngrok URL
              run: |
                URL=$(curl -s http://localhost:4040/api/tunnels | jq -r '.tunnels[0].public_url')
                echo "🔗 Public URL: $URL"

            # ✅ Keep ngrok Running
            - name: Keep Server Alive
              run: |
                while true; do
                    curl -s http://localhost:4040/api/tunnels
                    sleep 30
                done
                
